# Generated by Django 5.0.4 on 2024-05-15 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.block'),
        ),
    ]
